### ISSUE TITLE
Separate Title and Artist columns

### ISSUE THREAD

**Issue by NutritiousCookie** [szymonszewcjr/legacyLook#3]
Currently, playlists show the track title and artist in the same column. Before 2021 these were separate columns. It is a minor annoyance, but I believe they could be changed back with a bit of js trickery to pull artist names into a new column.

**Comment by szymonszewcjr** [comment]
Yes, this would certainly be possible, but would require quite a lot of work.
The thing is, spotify likes to throw errors when you mess about in it's DOM too much. Since the script would have to add new column, to each row, it would more often than not just error out.

Also I have tried this already, and adding new column inbetween columns causes last column (song length) to dissapear, spotify's css is written this way, and does not really allow me to make it work easily.

If I tried hard enough, I could make it work, but it would be hard to make it stable.

So for now I'm not planning on adding this, maybe I could poke around when I have more time on my hands.
